// File: tcol_business_examples.go
// Package: examples
// Title: TCOL Business Use Case Examples
// Description: Comprehensive business scenarios demonstrating TCOL usage
//              in real-world enterprise environments including customer
//              management, invoicing, project management, and reporting.
// Author: msto63 with Claude Opus 4.0
// Version: v0.1.0
// Created: 2025-07-26
// Modified: 2025-07-26

package examples

import (
	"fmt"
	"strings"
	"time"
)

// BusinessScenario represents a complete business use case
type BusinessScenario struct {
	Name        string
	Description string
	Commands    []string
	Context     map[string]interface{}
}

// TCOLBusinessExamples demonstrates real-world business scenarios
type TCOLBusinessExamples struct {
	scenarios []BusinessScenario
}

// NewBusinessExamples creates a new business examples instance
func NewBusinessExamples() *TCOLBusinessExamples {
	return &TCOLBusinessExamples{
		scenarios: make([]BusinessScenario, 0),
	}
}

// CustomerLifecycleManagement demonstrates complete customer management workflow
func (demo *TCOLBusinessExamples) CustomerLifecycleManagement() BusinessScenario {
	scenario := BusinessScenario{
		Name:        "Customer Lifecycle Management",
		Description: "Complete workflow from prospect to active customer including onboarding, service delivery, and retention",
		Commands: []string{
			"// === PROSPECT PHASE ===",
			"// Create new prospect from lead",
			"PROSPECT.CREATE name=\"TechStart GmbH\" source=\"website\" contact=\"info@techstart.de\"",
			"PROSPECT:last_created:industry=\"Technology\" :employees=25 :revenue_estimate=500000",
			"",
			"// Qualify prospect",
			"PROSPECT:last_created.QUALIFY criteria=\"budget,authority,need,timeline\"",
			"PROSPECT:last_created:qualification_score=85 :qualified_date=\"2024-07-26\"",
			"",
			"// === CUSTOMER CONVERSION ===",
			"// Convert qualified prospect to customer",
			"CUSTOMER.CREATE from_prospect=last_created type=\"B2B\" credit_limit=50000",
			"CUSTOMER:last_created:payment_terms=\"NET30\" :preferred_contact=\"email\"",
			"",
			"// Set up customer hierarchy",
			"CUSTOMER:last_created:parent_company=\"TechStart Holdings\" :subsidiary=false",
			"CONTACT.CREATE customer_id=last_created name=\"John Schmidt\" role=\"CFO\" email=\"j.schmidt@techstart.de\"",
			"CONTACT.CREATE customer_id=last_created name=\"Maria Weber\" role=\"Procurement\" email=\"m.weber@techstart.de\"",
			"",
			"// === ONBOARDING PROCESS ===",
			"// Create onboarding tasks",
			"TASK.CREATE title=\"Customer Welcome Package\" assignee=\"sales.team\" customer_id=last_created",
			"TASK.CREATE title=\"Technical Integration Setup\" assignee=\"tech.team\" customer_id=last_created",
			"TASK.CREATE title=\"Account Manager Assignment\" assignee=\"account.mgmt\" customer_id=last_created",
			"",
			"// Send welcome communications",
			"EMAIL.SEND customer_id=last_created template=\"welcome_b2b\" personalization=true",
			"DOCUMENT.GENERATE customer_id=last_created template=\"service_agreement\" status=\"draft\"",
			"",
			"// === ACTIVE RELATIONSHIP ===",
			"// Regular business operations",
			"ORDER.CREATE customer_id=last_created items=\"SRV-001,SRV-002\" amount=15000",
			"INVOICE.CREATE order_id=last_created due_date=\"2024-08-25\" payment_terms=\"NET30\"",
			"",
			"// Track customer satisfaction",
			"SURVEY.SEND customer_id=last_created type=\"satisfaction\" trigger=\"post_delivery\"",
			"CUSTOMER:last_created:satisfaction_score=4.2 :last_survey_date=\"2024-07-26\"",
			"",
			"// === RETENTION AND GROWTH ===",
			"// Monitor customer health",
			"CUSTOMER[satisfaction_score<3.0].LIST | ALERT.CREATE priority=\"high\" assignee=\"account.mgmt\"",
			"CUSTOMER[last_order_date<\"2024-04-01\"].LIST | TASK.CREATE title=\"Re-engagement Campaign\"",
			"",
			"// Upselling opportunities",
			"CUSTOMER[annual_revenue>100000,service_level=\"basic\"].LIST | OPPORTUNITY.CREATE type=\"upsell\"",
			"CUSTOMER:last_created.ANALYZE usage_patterns=true growth_potential=true",
		},
		Context: map[string]interface{}{
			"industry":      "B2B Software Services",
			"scenario_type": "Customer Lifecycle",
			"complexity":    "High",
			"duration":      "3-6 months",
		},
	}
	
	demo.scenarios = append(demo.scenarios, scenario)
	demo.logScenario(scenario)
	return scenario
}

// InvoiceProcessingWorkflow demonstrates comprehensive invoice management
func (demo *TCOLBusinessExamples) InvoiceProcessingWorkflow() BusinessScenario {
	scenario := BusinessScenario{
		Name:        "Invoice Processing Workflow",
		Description: "End-to-end invoice lifecycle from creation to payment including approval, sending, reminders, and collections",
		Commands: []string{
			"// === INVOICE CREATION ===",
			"// Create invoice from order",
			"ORDER.APPROVE order_id=\"ORD-2024-156\" approver=\"manager.finance\"",
			"INVOICE.CREATE order_id=\"ORD-2024-156\" type=\"standard\" currency=\"EUR\"",
			"",
			"// Add invoice details",
			"INVOICE:last_created:invoice_number=\"INV-2024-001578\" :invoice_date=\"2024-07-26\"",
			"INVOICE:last_created:due_date=\"2024-08-25\" :payment_terms=\"NET30\"",
			"INVOICE:last_created:tax_rate=0.19 :discount_percent=5.0",
			"",
			"// Add line items",
			"INVOICE.ADD-ITEM invoice_id=last_created product=\"SRV-CONSULTING\" quantity=40 unit_price=150.00",
			"INVOICE.ADD-ITEM invoice_id=last_created product=\"SRV-SUPPORT\" quantity=1 unit_price=2400.00",
			"INVOICE.ADD-ITEM invoice_id=last_created product=\"LIC-SOFTWARE\" quantity=10 unit_price=299.00",
			"",
			"// === APPROVAL WORKFLOW ===",
			"// Route for approval based on amount",
			"IF INVOICE:last_created:total_amount>10000 THEN {",
			"    APPROVAL.REQUEST invoice_id=last_created approver=\"director.finance\" level=\"high\"",
			"} ELSE {",
			"    APPROVAL.REQUEST invoice_id=last_created approver=\"manager.finance\" level=\"standard\"",
			"}",
			"",
			"// Approval process",
			"APPROVAL.REVIEW invoice_id=last_created reviewer=\"manager.finance\" status=\"approved\"",
			"INVOICE:last_created:approval_date=\"2024-07-26\" :approved_by=\"manager.finance\"",
			"",
			"// === INVOICE DISPATCH ===",
			"// Finalize and send invoice",
			"INVOICE.FINALIZE invoice_id=last_created",
			"INVOICE.SEND invoice_id=last_created method=\"email\" copy_accounting=true",
			"",
			"// Track delivery",
			"INVOICE:last_created:sent_date=\"2024-07-26\" :delivery_status=\"delivered\"",
			"CUSTOMER.NOTIFY customer_id=invoice.customer_id message=\"Invoice sent\" method=\"email\"",
			"",
			"// === PAYMENT TRACKING ===",
			"// Monitor payment status",
			"INVOICE[due_date<=\"2024-08-25\",status=\"sent\"].LIST | REPORT.GENERATE type=\"payment_due\"",
			"",
			"// Automated reminders",
			"SCHEDULE.CREATE trigger=\"due_date-7\" command=\"INVOICE.SEND-REMINDER type='friendly'\"",
			"SCHEDULE.CREATE trigger=\"due_date+1\" command=\"INVOICE.SEND-REMINDER type='overdue'\"",
			"SCHEDULE.CREATE trigger=\"due_date+30\" command=\"INVOICE.SEND-REMINDER type='final_notice'\"",
			"",
			"// === PAYMENT PROCESSING ===",
			"// Record payment",
			"PAYMENT.CREATE invoice_id=last_created amount=9282.00 method=\"bank_transfer\"",
			"PAYMENT:last_created:payment_date=\"2024-08-20\" :reference=\"TXN-789456123\"",
			"INVOICE:last_created:status=\"paid\" :paid_date=\"2024-08-20\" :paid_amount=9282.00",
			"",
			"// Handle partial payments",
			"IF PAYMENT:last_created:amount < INVOICE:last_created:total_amount THEN {",
			"    INVOICE:last_created:status=\"partially_paid\"",
			"    TASK.CREATE title=\"Follow up partial payment\" assignee=\"accounting.team\"",
			"}",
			"",
			"// === COLLECTIONS PROCESS ===",
			"// Overdue invoice management",
			"INVOICE[status=\"overdue\",days_overdue>30].LIST | COLLECTIONS.ASSIGN priority=\"medium\"",
			"INVOICE[status=\"overdue\",days_overdue>60].LIST | COLLECTIONS.ASSIGN priority=\"high\"",
			"INVOICE[status=\"overdue\",days_overdue>90].LIST | COLLECTIONS.ASSIGN priority=\"critical\"",
			"",
			"// Collections actions",
			"COLLECTIONS.CALL customer_id=invoice.customer_id outcome=\"payment_promised\" date=\"2024-08-30\"",
			"COLLECTIONS.EMAIL customer_id=invoice.customer_id template=\"formal_demand\" cc=\"legal.team\"",
			"",
			"// === REPORTING AND ANALYTICS ===",
			"// Generate financial reports",
			"REPORT.GENERATE type=\"aging_report\" period=\"2024-07\" format=\"excel\"",
			"REPORT.GENERATE type=\"revenue_recognition\" period=\"2024-Q3\" basis=\"accrual\"",
			"ANALYTICS.CALCULATE metric=\"days_sales_outstanding\" period=\"rolling_3_months\"",
		},
		Context: map[string]interface{}{
			"process_type":    "Financial Operations",
			"automation_level": "High",
			"compliance":      "SOX, GDPR",
			"integration":     "ERP, Banking, CRM",
		},
	}
	
	demo.scenarios = append(demo.scenarios, scenario)
	demo.logScenario(scenario)
	return scenario
}

// ProjectManagementScenario demonstrates project and task management
func (demo *TCOLBusinessExamples) ProjectManagementScenario() BusinessScenario {
	scenario := BusinessScenario{
		Name:        "Enterprise Project Management",
		Description: "Complex project management including resource allocation, milestone tracking, risk management, and team coordination",
		Commands: []string{
			"// === PROJECT INITIATION ===",
			"// Create new project",
			"PROJECT.CREATE name=\"Digital Transformation Initiative\" type=\"strategic\"",
			"PROJECT:last_created:start_date=\"2024-08-01\" :target_end_date=\"2025-02-28\"",
			"PROJECT:last_created:budget=500000 :currency=\"EUR\" :priority=\"high\"",
			"PROJECT:last_created:sponsor=\"CEO\" :manager=\"john.doe\" :status=\"planning\"",
			"",
			"// Define project phases",
			"PHASE.CREATE project_id=last_created name=\"Analysis & Planning\" duration=30",
			"PHASE.CREATE project_id=last_created name=\"Design & Development\" duration=90",
			"PHASE.CREATE project_id=last_created name=\"Testing & QA\" duration=45",
			"PHASE.CREATE project_id=last_created name=\"Deployment & Training\" duration=30",
			"PHASE.CREATE project_id=last_created name=\"Go-Live & Support\" duration=15",
			"",
			"// === TEAM SETUP ===",
			"// Assign project team",
			"TEAM.CREATE project_id=last_created name=\"DT Core Team\" type=\"primary\"",
			"TEAM.ADD-MEMBER team_id=last_created user_id=\"john.doe\" role=\"Project Manager\"",
			"TEAM.ADD-MEMBER team_id=last_created user_id=\"maria.schmidt\" role=\"Technical Lead\"",
			"TEAM.ADD-MEMBER team_id=last_created user_id=\"alex.mueller\" role=\"Business Analyst\"",
			"TEAM.ADD-MEMBER team_id=last_created user_id=\"sarah.weber\" role=\"QA Manager\"",
			"",
			"// Define team responsibilities",
			"ROLE.DEFINE project_id=last_created role=\"Project Manager\" permissions=\"all\"",
			"ROLE.DEFINE project_id=last_created role=\"Technical Lead\" permissions=\"development,architecture\"",
			"ROLE.DEFINE project_id=last_created role=\"Business Analyst\" permissions=\"requirements,documentation\"",
			"",
			"// === TASK PLANNING ===",
			"// Create work breakdown structure",
			"TASK.CREATE project_id=last_created title=\"Requirements Gathering\" phase=\"Analysis & Planning\"",
			"TASK:last_created:assignee=\"alex.mueller\" :effort_hours=80 :priority=1",
			"TASK:last_created:start_date=\"2024-08-01\" :due_date=\"2024-08-15\"",
			"",
			"TASK.CREATE project_id=last_created title=\"System Architecture Design\" phase=\"Design & Development\"",
			"TASK:last_created:assignee=\"maria.schmidt\" :effort_hours=120 :priority=1",
			"TASK:last_created:dependencies=\"Requirements Gathering\"",
			"",
			"TASK.CREATE project_id=last_created title=\"Database Schema Design\" phase=\"Design & Development\"",
			"TASK:last_created:assignee=\"database.team\" :effort_hours=60 :priority=2",
			"",
			"// Create subtasks",
			"SUBTASK.CREATE parent_task=last_created title=\"Entity Relationship Modeling\" effort_hours=20",
			"SUBTASK.CREATE parent_task=last_created title=\"Performance Optimization\" effort_hours=15",
			"SUBTASK.CREATE parent_task=last_created title=\"Data Migration Planning\" effort_hours=25",
			"",
			"// === RESOURCE MANAGEMENT ===",
			"// Allocate resources",
			"RESOURCE.ALLOCATE project_id=last_created resource_type=\"human\" user_id=\"john.doe\" allocation=100",
			"RESOURCE.ALLOCATE project_id=last_created resource_type=\"human\" user_id=\"maria.schmidt\" allocation=80",
			"RESOURCE.ALLOCATE project_id=last_created resource_type=\"budget\" category=\"software_licenses\" amount=25000",
			"RESOURCE.ALLOCATE project_id=last_created resource_type=\"budget\" category=\"external_consultants\" amount=75000",
			"",
			"// Check resource conflicts",
			"RESOURCE.CHECK-CONFLICTS user_id=\"maria.schmidt\" period=\"2024-08-01:2024-10-31\"",
			"RESOURCE.OPTIMIZE project_id=last_created criteria=\"cost,time,quality\"",
			"",
			"// === PROJECT EXECUTION ===",
			"// Start project execution",
			"PROJECT:last_created:status=\"active\" :actual_start_date=\"2024-08-01\"",
			"TASK[phase=\"Analysis & Planning\"].START",
			"",
			"// Daily progress tracking",
			"TASK:requirements_gathering:progress=25 :hours_spent=20 :notes=\"Stakeholder interviews completed\"",
			"TASK:requirements_gathering.LOG-TIME user_id=\"alex.mueller\" hours=8 activity=\"stakeholder_interviews\"",
			"",
			"// Milestone tracking",
			"MILESTONE.CREATE project_id=last_created name=\"Requirements Approved\" date=\"2024-08-15\"",
			"MILESTONE.CREATE project_id=last_created name=\"Design Complete\" date=\"2024-09-30\"",
			"MILESTONE.CREATE project_id=last_created name=\"Development Complete\" date=\"2024-12-15\"",
			"",
			"// === RISK MANAGEMENT ===",
			"// Identify and manage risks",
			"RISK.CREATE project_id=last_created title=\"Key Developer Unavailability\" probability=\"medium\" impact=\"high\"",
			"RISK:last_created:mitigation=\"Cross-train team members\" :owner=\"john.doe\"",
			"",
			"RISK.CREATE project_id=last_created title=\"Scope Creep\" probability=\"high\" impact=\"medium\"",
			"RISK:last_created:mitigation=\"Formal change control process\" :owner=\"alex.mueller\"",
			"",
			"// Risk monitoring",
			"RISK[probability=\"high\"].LIST | ALERT.CREATE assignee=\"project.manager\"",
			"RISK[impact=\"high\",status=\"open\"].ESCALATE level=\"senior_management\"",
			"",
			"// === PROJECT MONITORING ===",
			"// Generate project reports",
			"REPORT.GENERATE project_id=last_created type=\"status\" period=\"weekly\" recipients=\"stakeholders\"",
			"REPORT.GENERATE project_id=last_created type=\"budget_variance\" threshold=10",
			"REPORT.GENERATE project_id=last_created type=\"resource_utilization\" format=\"dashboard\"",
			"",
			"// Performance metrics",
			"METRICS.CALCULATE project_id=last_created metric=\"schedule_performance_index\"",
			"METRICS.CALCULATE project_id=last_created metric=\"cost_performance_index\"",
			"METRICS.CALCULATE project_id=last_created metric=\"earned_value\"",
			"",
			"// === PROJECT CLOSURE ===",
			"// Complete project phases",
			"PHASE[name=\"Analysis & Planning\"].COMPLETE completion_date=\"2024-08-30\"",
			"LESSONS.CAPTURE project_id=last_created phase=\"Analysis & Planning\" type=\"best_practices\"",
			"",
			"// Final project closure",
			"PROJECT:last_created.COMPLETE actual_end_date=\"2025-02-28\" final_cost=485000",
			"RETROSPECTIVE.CONDUCT project_id=last_created participants=\"core_team,stakeholders\"",
			"KNOWLEDGE.TRANSFER project_id=last_created target_team=\"operations\" documentation=complete",
		},
		Context: map[string]interface{}{
			"methodology":    "Hybrid Agile-Waterfall",
			"team_size":      "15-20 members",
			"duration":       "7 months",
			"budget":         "500,000 EUR",
			"risk_level":     "Medium-High",
		},
	}
	
	demo.scenarios = append(demo.scenarios, scenario)
	demo.logScenario(scenario)
	return scenario
}

// SalesProcessAutomation demonstrates sales pipeline and CRM operations
func (demo *TCOLBusinessExamples) SalesProcessAutomation() BusinessScenario {
	scenario := BusinessScenario{
		Name:        "Sales Process Automation",
		Description: "Complete sales pipeline from lead generation to deal closure including opportunity management, forecasting, and commission tracking",
		Commands: []string{
			"// === LEAD GENERATION ===",
			"// Import leads from various sources",
			"LEAD.IMPORT source=\"website_form\" file=\"web_leads_2024_07.csv\" auto_assign=true",
			"LEAD.IMPORT source=\"trade_show\" event=\"TechExpo2024\" booth=\"B-157\"",
			"LEAD.IMPORT source=\"cold_outreach\" campaign=\"Q3_Enterprise_Campaign\"",
			"",
			"// Lead enrichment and scoring",
			"LEAD[source=\"website_form\"].ENRICH data_provider=\"clearbit\" fields=\"company_size,industry,revenue\"",
			"LEAD.SCORE-ALL model=\"enterprise_2024\" factors=\"company_size,budget,timeline,authority\"",
			"",
			"// Automatic lead assignment",
			"LEAD[score>=75,region=\"EMEA\"].ASSIGN-TO user_id=\"sales.emea.senior\"",
			"LEAD[score>=50,score<75,region=\"EMEA\"].ASSIGN-TO user_id=\"sales.emea.junior\"",
			"LEAD[score<50].ASSIGN-TO user_id=\"marketing.nurture\"",
			"",
			"// === OPPORTUNITY CREATION ===",
			"// Qualify leads and create opportunities",
			"LEAD:lead_12345.QUALIFY criteria=\"BANT\" result=\"qualified\"",
			"OPPORTUNITY.CREATE from_lead=lead_12345 value=75000 probability=25",
			"OPPORTUNITY:last_created:stage=\"Discovery\" :close_date=\"2024-10-31\"",
			"OPPORTUNITY:last_created:products=\"Enterprise License,Professional Services\"",
			"",
			"// Set up opportunity team",
			"OPPORTUNITY.ADD-TEAM-MEMBER opp_id=last_created user_id=\"account.executive\" role=\"primary\"",
			"OPPORTUNITY.ADD-TEAM-MEMBER opp_id=last_created user_id=\"sales.engineer\" role=\"technical\"",
			"OPPORTUNITY.ADD-TEAM-MEMBER opp_id=last_created user_id=\"sales.manager\" role=\"oversight\"",
			"",
			"// === SALES ACTIVITIES ===",
			"// Schedule and track activities",
			"ACTIVITY.CREATE opportunity_id=last_created type=\"discovery_call\" date=\"2024-07-30\"",
			"ACTIVITY:last_created:participants=\"customer.cto,customer.cfo\" :duration=60",
			"ACTIVITY:last_created:objectives=\"understand_requirements,budget_qualification\"",
			"",
			"ACTIVITY.CREATE opportunity_id=last_created type=\"technical_demo\" date=\"2024-08-05\"",
			"ACTIVITY.CREATE opportunity_id=last_created type=\"proposal_presentation\" date=\"2024-08-15\"",
			"ACTIVITY.CREATE opportunity_id=last_created type=\"contract_negotiation\" date=\"2024-09-01\"",
			"",
			"// Track activity outcomes",
			"ACTIVITY:discovery_call:outcome=\"positive\" :next_steps=\"technical_demo_scheduled\"",
			"ACTIVITY:discovery_call.ADD-NOTE \"Customer confirmed budget of 75K, decision timeline Q4\"",
			"",
			"// === PROPOSAL AND QUOTING ===",
			"// Generate proposals",
			"PROPOSAL.CREATE opportunity_id=last_created template=\"enterprise_standard\"",
			"PROPOSAL:last_created:valid_until=\"2024-09-30\" :discount_percent=10",
			"",
			"// Add proposal line items",
			"PROPOSAL.ADD-ITEM proposal_id=last_created product=\"ENT-LICENSE-50\" quantity=1 price=45000",
			"PROPOSAL.ADD-ITEM proposal_id=last_created product=\"PROF-SERVICES\" quantity=200 price=150",
			"PROPOSAL.ADD-ITEM proposal_id=last_created product=\"SUPPORT-PREMIUM\" quantity=1 price=12000",
			"",
			"// Proposal approval workflow",
			"PROPOSAL.REQUEST-APPROVAL proposal_id=last_created approver=\"sales.director\" reason=\"discount>5%\"",
			"PROPOSAL:last_created:approval_status=\"approved\" :approved_by=\"sales.director\"",
			"",
			"// Send proposal",
			"PROPOSAL.SEND proposal_id=last_created method=\"email\" tracking=true",
			"PROPOSAL:last_created:sent_date=\"2024-08-16\" :recipient=\"customer.procurement\"",
			"",
			"// === PIPELINE MANAGEMENT ===",
			"// Update opportunity stages",
			"OPPORTUNITY:last_created:stage=\"Proposal\" :probability=60 :last_activity=\"2024-08-16\"",
			"OPPORTUNITY.ADD-NOTE opp_id=last_created \"Proposal sent, customer reviewing internally\"",
			"",
			"// Competitive analysis",
			"COMPETITOR.ADD opportunity_id=last_created name=\"CompetitorX\" strengths=\"price\" weaknesses=\"features\"",
			"BATTLECARD.GENERATE opportunity_id=last_created competitor=\"CompetitorX\"",
			"",
			"// Pipeline forecasting",
			"FORECAST.CALCULATE period=\"2024-Q4\" team=\"enterprise_sales\" confidence_level=80",
			"FORECAST.ANALYZE opportunity_id=last_created factors=\"stage,probability,close_date,activities\"",
			"",
			"// === DEAL NEGOTIATION ===",
			"// Track negotiation points",
			"NEGOTIATION.CREATE opportunity_id=last_created items=\"price,terms,timeline\"",
			"NEGOTIATION.ADD-POINT point=\"price\" our_position=67500 their_position=60000 status=\"open\"",
			"NEGOTIATION.ADD-POINT point=\"payment_terms\" our_position=\"NET30\" their_position=\"NET60\" status=\"agreed\"",
			"",
			"// Legal review",
			"CONTRACT.REQUEST-REVIEW opportunity_id=last_created reviewers=\"legal.team\" priority=\"standard\"",
			"CONTRACT:last_created:review_status=\"approved\" :conditions=\"standard_enterprise_terms\"",
			"",
			"// === DEAL CLOSURE ===",
			"// Close won opportunity",
			"OPPORTUNITY:last_created:stage=\"Closed Won\" :probability=100 :close_date=\"2024-09-15\"",
			"OPPORTUNITY:last_created:actual_value=67500 :won_reason=\"best_technical_fit\"",
			"",
			"// Generate order and contract",
			"ORDER.CREATE opportunity_id=last_created customer_id=opp.customer_id total=67500",
			"CONTRACT.GENERATE order_id=last_created template=\"enterprise_standard\" terms=\"NET30\"",
			"",
			"// === POST-SALE ACTIVITIES ===",
			"// Commission calculation",
			"COMMISSION.CALCULATE opportunity_id=last_created sales_rep=\"account.executive\" rate=0.08",
			"COMMISSION.CALCULATE opportunity_id=last_created sales_engineer=\"tech.support\" rate=0.02",
			"",
			"// Customer handoff",
			"HANDOFF.CREATE from_team=\"sales\" to_team=\"customer_success\" customer_id=opp.customer_id",
			"HANDOFF.ADD-NOTES \"Customer priority: fast implementation, key contact: John Smith (CTO)\"",
			"",
			"// Update customer record",
			"CUSTOMER:opp.customer_id:status=\"active\" :acquisition_date=\"2024-09-15\"",
			"CUSTOMER:opp.customer_id:lifetime_value=67500 :acquisition_cost=8500",
			"",
			"// === SALES ANALYTICS ===",
			"// Performance metrics",
			"ANALYTICS.CALCULATE metric=\"conversion_rate\" period=\"2024-Q3\" team=\"enterprise_sales\"",
			"ANALYTICS.CALCULATE metric=\"average_deal_size\" period=\"2024-Q3\" segment=\"enterprise\"",
			"ANALYTICS.CALCULATE metric=\"sales_cycle_length\" period=\"2024-Q3\"",
			"",
			"// Sales reports",
			"REPORT.GENERATE type=\"pipeline_report\" period=\"2024-Q3\" format=\"executive_summary\"",
			"REPORT.GENERATE type=\"win_loss_analysis\" period=\"2024-Q3\" segments=\"by_industry,by_size\"",
			"REPORT.GENERATE type=\"commission_summary\" period=\"2024-Q3\" team=\"all_sales\"",
		},
		Context: map[string]interface{}{
			"sales_model":    "Enterprise B2B",
			"cycle_length":   "3-6 months",
			"deal_size":      "50K-500K EUR",
			"team_structure": "Account Executive + Sales Engineer",
			"CRM_integration": "Salesforce, HubSpot",
		},
	}
	
	demo.scenarios = append(demo.scenarios, scenario)
	demo.logScenario(scenario)
	return scenario
}

// InventoryAndSupplyChain demonstrates inventory management and supply chain operations
func (demo *TCOLBusinessExamples) InventoryAndSupplyChain() BusinessScenario {
	scenario := BusinessScenario{
		Name:        "Inventory and Supply Chain Management",
		Description: "Complex inventory management including procurement, stock control, demand forecasting, and supplier management",
		Commands: []string{
			"// === INVENTORY SETUP ===",
			"// Create product catalog",
			"PRODUCT.CREATE sku=\"LAPTOP-DEL-001\" name=\"Dell Laptop Business\" category=\"hardware\"",
			"PRODUCT:last_created:cost=800 :price=1200 :weight=2.1 :supplier=\"Dell Inc\"",
			"PRODUCT:last_created:min_stock=50 :max_stock=200 :reorder_point=75",
			"",
			"PRODUCT.CREATE sku=\"MON-SAMSUNG-24\" name=\"Samsung 24\" Monitor\" category=\"peripherals\"",
			"PRODUCT:last_created:cost=180 :price=280 :reorder_point=25 :lead_time_days=14",
			"",
			"// Set up warehouse locations",
			"WAREHOUSE.CREATE code=\"WH-MAIN\" name=\"Main Warehouse\" location=\"Berlin, Germany\"",
			"WAREHOUSE:last_created:capacity=10000 :type=\"distribution\" :manager=\"warehouse.manager\"",
			"",
			"WAREHOUSE.CREATE code=\"WH-NORTH\" name=\"Northern Depot\" location=\"Hamburg, Germany\"",
			"WAREHOUSE.CREATE code=\"WH-SOUTH\" name=\"Southern Depot\" location=\"Munich, Germany\"",
			"",
			"// === STOCK MANAGEMENT ===",
			"// Initial stock intake",
			"STOCK.RECEIVE warehouse=\"WH-MAIN\" sku=\"LAPTOP-DEL-001\" quantity=150 cost=800",
			"STOCK:last_received:lot_number=\"LOT-2024-071\" :expiry_date=\"2027-07-26\" :quality_status=\"passed\"",
			"",
			"STOCK.RECEIVE warehouse=\"WH-MAIN\" sku=\"MON-SAMSUNG-24\" quantity=80 cost=180",
			"STOCK.TRANSFER from_warehouse=\"WH-MAIN\" to_warehouse=\"WH-NORTH\" sku=\"LAPTOP-DEL-001\" quantity=30",
			"",
			"// Stock adjustments",
			"STOCK.ADJUST warehouse=\"WH-MAIN\" sku=\"LAPTOP-DEL-001\" quantity=-2 reason=\"damaged_in_transit\"",
			"STOCK.COUNT warehouse=\"WH-MAIN\" sku=\"all\" cycle=\"monthly\" assignee=\"inventory.team\"",
			"",
			"// === DEMAND FORECASTING ===",
			"// Analyze historical demand",
			"DEMAND.ANALYZE sku=\"LAPTOP-DEL-001\" period=\"last_12_months\" seasonality=true",
			"DEMAND.FORECAST sku=\"LAPTOP-DEL-001\" horizon=\"3_months\" method=\"exponential_smoothing\"",
			"",
			"// Set up automated reordering",
			"REORDER.RULE-CREATE sku=\"LAPTOP-DEL-001\" trigger=\"stock_below_reorder_point\"",
			"REORDER.RULE-CREATE sku=\"all\" trigger=\"forecast_high_demand\" lead_time_buffer=7",
			"",
			"// === SUPPLIER MANAGEMENT ===",
			"// Supplier setup",
			"SUPPLIER.CREATE name=\"Dell Inc\" type=\"manufacturer\" rating=\"A\"",
			"SUPPLIER:last_created:payment_terms=\"NET45\" :lead_time_days=21 :min_order=10000",
			"SUPPLIER:last_created:contact=\"procurement@dell.com\" :phone=\"+49-89-12345\"",
			"",
			"SUPPLIER.CREATE name=\"Samsung Electronics\" type=\"manufacturer\" rating=\"A\"",
			"SUPPLIER:last_created:payment_terms=\"NET30\" :lead_time_days=14",
			"",
			"// Supplier performance tracking",
			"SUPPLIER.RATE supplier=\"Dell Inc\" delivery_performance=95 quality_rating=98 price_competitiveness=85",
			"SUPPLIER.RATE supplier=\"Samsung Electronics\" delivery_performance=92 quality_rating=96",
			"",
			"// === PROCUREMENT PROCESS ===",
			"// Create purchase requisition",
			"REQUISITION.CREATE requester=\"sales.team\" urgency=\"normal\"",
			"REQUISITION.ADD-ITEM req_id=last_created sku=\"LAPTOP-DEL-001\" quantity=100 budget=85000",
			"REQUISITION.ADD-ITEM req_id=last_created sku=\"MON-SAMSUNG-24\" quantity=50 budget=10000",
			"",
			"// Approval workflow",
			"REQUISITION.SUBMIT req_id=last_created approver=\"procurement.manager\"",
			"REQUISITION:last_created:approval_status=\"approved\" :approved_date=\"2024-07-26\"",
			"",
			"// Create purchase orders",
			"PO.CREATE requisition_id=last_created supplier=\"Dell Inc\"",
			"PO:last_created:delivery_date=\"2024-08-16\" :payment_terms=\"NET45\" :shipping=\"CIF\"",
			"PO.ADD-ITEM po_id=last_created sku=\"LAPTOP-DEL-001\" quantity=100 unit_price=800",
			"",
			"PO.CREATE requisition_id=last_created supplier=\"Samsung Electronics\"",
			"PO.ADD-ITEM po_id=last_created sku=\"MON-SAMSUNG-24\" quantity=50 unit_price=180",
			"",
			"// Send purchase orders",
			"PO.SEND po_id=all_created method=\"email\" tracking=true",
			"PO[supplier=\"Dell Inc\"]:confirmation_required=true :follow_up_date=\"2024-07-28\"",
			"",
			"// === ORDER FULFILLMENT ===",
			"// Receive customer orders",
			"ORDER.CREATE customer_id=\"CUST-12345\" priority=\"standard\"",
			"ORDER.ADD-ITEM order_id=last_created sku=\"LAPTOP-DEL-001\" quantity=5 price=1200",
			"ORDER.ADD-ITEM order_id=last_created sku=\"MON-SAMSUNG-24\" quantity=10 price=280",
			"",
			"// Check stock availability",
			"STOCK.CHECK-AVAILABILITY order_id=last_created warehouse=\"WH-MAIN\"",
			"ORDER:last_created:stock_status=\"available\" :allocated_warehouse=\"WH-MAIN\"",
			"",
			"// Pick and pack",
			"PICKING.CREATE order_id=last_created warehouse=\"WH-MAIN\" picker=\"warehouse.staff\"",
			"PICKING:last_created:pick_status=\"completed\" :picked_date=\"2024-07-26\"",
			"",
			"PACKING.CREATE picking_id=last_created packer=\"warehouse.staff\"",
			"PACKING:last_created:package_count=2 :total_weight=12.5 :carrier=\"DHL\"",
			"",
			"// === SHIPPING AND LOGISTICS ===",
			"// Arrange shipping",
			"SHIPMENT.CREATE order_id=last_created carrier=\"DHL\" service=\"EXPRESS\"",
			"SHIPMENT:last_created:tracking_number=\"DHL123456789\" :estimated_delivery=\"2024-07-28\"",
			"",
			"// Update stock levels",
			"STOCK.REDUCE warehouse=\"WH-MAIN\" sku=\"LAPTOP-DEL-001\" quantity=5 reason=\"customer_shipment\"",
			"STOCK.REDUCE warehouse=\"WH-MAIN\" sku=\"MON-SAMSUNG-24\" quantity=10 reason=\"customer_shipment\"",
			"",
			"// Track delivery",
			"TRACKING.UPDATE shipment_id=last_created status=\"in_transit\" location=\"Berlin Hub\"",
			"TRACKING.UPDATE shipment_id=last_created status=\"delivered\" date=\"2024-07-28\"",
			"",
			"// === INVENTORY OPTIMIZATION ===",
			"// ABC analysis",
			"ANALYSIS.ABC-CLASSIFY criteria=\"revenue_contribution\" period=\"last_12_months\"",
			"PRODUCT[abc_class=\"A\"].UPDATE min_stock=multiply(1.2) max_stock=multiply(1.5)",
			"",
			"// Slow-moving stock analysis",
			"ANALYSIS.SLOW-MOVERS period=\"last_6_months\" threshold=\"turns<4\"",
			"PRODUCT[slow_moving=true].DISCOUNT percentage=15 campaign=\"inventory_clearance\"",
			"",
			"// Carrying cost optimization",
			"ANALYSIS.CARRYING-COST warehouse=\"all\" include=\"storage,insurance,obsolescence\"",
			"OPTIMIZATION.SUGGEST focus=\"reduce_carrying_cost\" constraints=\"service_level>=95%\"",
			"",
			"// === REPORTING AND KPIs ===",
			"// Inventory reports",
			"REPORT.GENERATE type=\"stock_levels\" warehouse=\"all\" threshold=\"below_reorder_point\"",
			"REPORT.GENERATE type=\"inventory_valuation\" method=\"FIFO\" date=\"2024-07-26\"",
			"REPORT.GENERATE type=\"turnover_analysis\" period=\"2024-Q2\" group_by=\"category\"",
			"",
			"// Performance metrics",
			"KPI.CALCULATE metric=\"inventory_turnover\" period=\"rolling_12_months\"",
			"KPI.CALCULATE metric=\"stockout_rate\" period=\"2024-Q2\" target=\"<2%\"",
			"KPI.CALCULATE metric=\"order_fill_rate\" period=\"2024-Q2\" target=\">98%\"",
			"KPI.CALCULATE metric=\"carrying_cost_percentage\" period=\"2024-Q2\"",
			"",
			"// Supplier performance metrics",
			"SUPPLIER.KPI supplier=\"Dell Inc\" metrics=\"on_time_delivery,quality_rate,cost_variance\"",
			"SUPPLIER.SCORECARD period=\"2024-Q2\" rank_by=\"overall_performance\"",
		},
		Context: map[string]interface{}{
			"industry":        "IT Equipment Distribution",
			"warehouse_count": "3 locations",
			"sku_count":       "500+ products",
			"automation":      "WMS, EDI, RFID",
			"compliance":      "ISO 9001, GDPR",
		},
	}
	
	demo.scenarios = append(demo.scenarios, scenario)
	demo.logScenario(scenario)
	return scenario
}

// HRandTalentManagement demonstrates human resources and talent management
func (demo *TCOLBusinessExamples) HRandTalentManagement() BusinessScenario {
	scenario := BusinessScenario{
		Name:        "HR and Talent Management",
		Description: "Comprehensive HR operations including recruitment, onboarding, performance management, career development, and employee lifecycle",
		Commands: []string{
			"// === RECRUITMENT PROCESS ===",
			"// Create job requisition",
			"REQUISITION.CREATE position=\"Senior Software Engineer\" department=\"Engineering\"",
			"REQUISITION:last_created:headcount=2 :budget=120000 :priority=\"high\"",
			"REQUISITION:last_created:skills=\"Java,React,PostgreSQL,AWS\" :experience_years=5",
			"REQUISITION:last_created:manager=\"engineering.lead\" :recruiter=\"hr.recruiter\"",
			"",
			"// Approval workflow",
			"REQUISITION.REQUEST-APPROVAL req_id=last_created approver=\"engineering.director\"",
			"REQUISITION:last_created:approval_status=\"approved\" :budget_approved=120000",
			"",
			"// Job posting",
			"JOB.CREATE requisition_id=last_created title=\"Senior Software Engineer (Remote)\"",
			"JOB:last_created:location=\"Remote/Berlin\" :salary_range=\"80000-95000\"",
			"JOB:last_created:benefits=\"health,pension,flexible_hours\" :remote_friendly=true",
			"",
			"JOB.POST job_id=last_created channels=\"linkedin,xing,company_website,stackoverflow\"",
			"JOB:last_created:posted_date=\"2024-07-26\" :application_deadline=\"2024-08-26\"",
			"",
			"// === APPLICATION MANAGEMENT ===",
			"// Process applications",
			"APPLICATION.IMPORT source=\"linkedin\" job_id=last_created count=45",
			"APPLICATION.IMPORT source=\"company_website\" job_id=last_created count=23",
			"",
			"// Initial screening",
			"APPLICATION[job_id=last_created].SCREEN criteria=\"skills_match,experience,location\"",
			"APPLICATION[screen_score>=75].UPDATE status=\"phone_screen_scheduled\"",
			"APPLICATION[screen_score<50].UPDATE status=\"rejected\" reason=\"insufficient_experience\"",
			"",
			"// Schedule interviews",
			"INTERVIEW.SCHEDULE application_id=\"APP-2024-1234\" type=\"phone_screen\" interviewer=\"hr.recruiter\"",
			"INTERVIEW:last_scheduled:date=\"2024-07-30\" :duration=30 :agenda=\"background,motivation\"",
			"",
			"INTERVIEW.SCHEDULE application_id=\"APP-2024-1234\" type=\"technical\" interviewer=\"engineering.lead\"",
			"INTERVIEW:last_scheduled:date=\"2024-08-02\" :duration=90 :agenda=\"coding,system_design\"",
			"",
			"// === INTERVIEW PROCESS ===",
			"// Conduct interviews",
			"INTERVIEW:phone_screen:status=\"completed\" :rating=\"strong_positive\"",
			"INTERVIEW:phone_screen.ADD-FEEDBACK \"Excellent communication, strong motivation, culture fit\"",
			"",
			"INTERVIEW:technical:status=\"completed\" :rating=\"positive\"",
			"INTERVIEW:technical.ADD-FEEDBACK \"Good technical skills, needs improvement in system design\"",
			"",
			"// Panel interview",
			"INTERVIEW.SCHEDULE application_id=\"APP-2024-1234\" type=\"panel\"",
			"INTERVIEW.ADD-INTERVIEWER interview_id=last_created interviewer=\"engineering.lead\"",
			"INTERVIEW.ADD-INTERVIEWER interview_id=last_created interviewer=\"product.manager\"",
			"INTERVIEW.ADD-INTERVIEWER interview_id=last_created interviewer=\"senior.engineer\"",
			"",
			"// Reference checks",
			"REFERENCE.REQUEST application_id=\"APP-2024-1234\" contact=\"previous.manager@company.com\"",
			"REFERENCE:last_created:status=\"positive\" :feedback=\"Strong performer, team player\"",
			"",
			"// === HIRING DECISION ===",
			"// Decision meeting",
			"DECISION.MEETING application_id=\"APP-2024-1234\" participants=\"hiring_committee\"",
			"DECISION:last_created:outcome=\"hire\" :compensation=85000 :start_date=\"2024-09-01\"",
			"",
			"// Make offer",
			"OFFER.CREATE application_id=\"APP-2024-1234\" salary=85000 benefits=\"standard_package\"",
			"OFFER:last_created:equity=1000 :vacation_days=25 :remote_policy=\"flexible\"",
			"OFFER:last_created:valid_until=\"2024-08-15\" :negotiation_room=5000",
			"",
			"OFFER.SEND offer_id=last_created method=\"email\" tracking=true",
			"OFFER:last_created:sent_date=\"2024-08-05\" :response_deadline=\"2024-08-15\"",
			"",
			"// Offer acceptance",
			"OFFER:last_created:status=\"accepted\" :accepted_date=\"2024-08-10\"",
			"OFFER:last_created:final_salary=87000 :negotiated_items=\"salary\"",
			"",
			"// === ONBOARDING PROCESS ===",
			"// Create employee record",
			"EMPLOYEE.CREATE from_application=\"APP-2024-1234\" employee_id=\"EMP-2024-156\"",
			"EMPLOYEE:last_created:first_name=\"John\" :last_name=\"Mueller\"",
			"EMPLOYEE:last_created:department=\"Engineering\" :position=\"Senior Software Engineer\"",
			"EMPLOYEE:last_created:manager=\"engineering.lead\" :start_date=\"2024-09-01\"",
			"",
			"// Onboarding checklist",
			"ONBOARDING.CREATE employee_id=last_created template=\"engineering_standard\"",
			"ONBOARDING.ADD-TASK employee_id=last_created task=\"IT Setup\" assignee=\"it.support\" due=\"day_1\"",
			"ONBOARDING.ADD-TASK employee_id=last_created task=\"Office Tour\" assignee=\"hr.team\" due=\"day_1\"",
			"ONBOARDING.ADD-TASK employee_id=last_created task=\"Team Introduction\" assignee=\"engineering.lead\" due=\"week_1\"",
			"ONBOARDING.ADD-TASK employee_id=last_created task=\"Security Training\" assignee=\"security.team\" due=\"week_2\"",
			"",
			"// Equipment allocation",
			"EQUIPMENT.ALLOCATE employee_id=last_created item=\"MacBook Pro\" specifications=\"16GB,512GB\"",
			"EQUIPMENT.ALLOCATE employee_id=last_created item=\"Monitor\" specifications=\"27inch,4K\"",
			"EQUIPMENT.ORDER employee_id=last_created delivery_date=\"2024-08-30\"",
			"",
			"// === PERFORMANCE MANAGEMENT ===",
			"// Set goals and objectives",
			"GOAL.CREATE employee_id=last_created type=\"quarterly\" period=\"2024-Q4\"",
			"GOAL:last_created:title=\"Complete project onboarding\" :weight=40 :metric=\"project_completion\"",
			"GOAL.CREATE employee_id=last_created title=\"Technical skill development\" weight=30",
			"GOAL.CREATE employee_id=last_created title=\"Team collaboration\" weight=30",
			"",
			"// Regular check-ins",
			"CHECKIN.SCHEDULE employee_id=last_created frequency=\"weekly\" duration=30",
			"CHECKIN.CREATE employee_id=last_created date=\"2024-09-08\" topics=\"progress,challenges,support\"",
			"CHECKIN:last_created:rating=\"on_track\" :notes=\"Good progress, needs mentoring on architecture\"",
			"",
			"// Performance reviews",
			"REVIEW.CREATE employee_id=last_created type=\"quarterly\" period=\"2024-Q4\"",
			"REVIEW:last_created:self_assessment=\"strong\" :manager_rating=\"exceeds\"",
			"REVIEW:last_created:strengths=\"technical_skills,collaboration\" :development_areas=\"system_design\"",
			"",
			"// === CAREER DEVELOPMENT ===",
			"// Individual development plan",
			"IDP.CREATE employee_id=last_created period=\"2024-2025\"",
			"IDP.ADD-OBJECTIVE employee_id=last_created objective=\"Technical Leadership\" timeline=\"12_months\"",
			"IDP.ADD-ACTION employee_id=last_created action=\"Complete system design course\" deadline=\"2024-12-31\"",
			"IDP.ADD-ACTION employee_id=last_created action=\"Lead technical project\" deadline=\"2025-06-30\"",
			"",
			"// Training and development",
			"TRAINING.ENROLL employee_id=last_created course=\"Advanced System Design\" provider=\"internal\"",
			"TRAINING.ENROLL employee_id=last_created course=\"Leadership Fundamentals\" provider=\"external\"",
			"TRAINING:system_design:completion_date=\"2024-12-15\" :grade=\"passed\" :credits=40",
			"",
			"// Mentoring program",
			"MENTORING.ASSIGN mentee=last_created mentor=\"senior.architect\" duration=\"6_months\"",
			"MENTORING:last_created:focus_areas=\"architecture,technical_leadership\" :meeting_frequency=\"bi_weekly\"",
			"",
			"// === COMPENSATION MANAGEMENT ===",
			"// Salary reviews",
			"COMPENSATION.REVIEW employee_id=last_created cycle=\"annual\" effective_date=\"2025-01-01\"",
			"COMPENSATION:last_created:current_salary=87000 :market_rate=92000 :performance_rating=\"exceeds\"",
			"COMPENSATION:last_created:recommended_increase=8 :new_salary=94000",
			"",
			"// Bonus calculations",
			"BONUS.CALCULATE employee_id=last_created type=\"performance\" period=\"2024\"",
			"BONUS:last_created:target_amount=8700 :performance_multiplier=1.15 :final_amount=10005",
			"",
			"// Equity management",
			"EQUITY.VEST employee_id=last_created vesting_date=\"2025-09-01\" shares=250",
			"EQUITY:last_created:total_vested=250 :remaining_unvested=750",
			"",
			"// === EMPLOYEE LIFECYCLE ===",
			"// Promotions",
			"PROMOTION.NOMINATE employee_id=last_created new_position=\"Staff Software Engineer\"",
			"PROMOTION:last_created:justification=\"Exceptional performance, technical leadership\"",
			"PROMOTION:last_created:approval_status=\"approved\" :effective_date=\"2025-07-01\"",
			"",
			"// Internal transfers",
			"TRANSFER.REQUEST employee_id=last_created target_department=\"Platform Engineering\"",
			"TRANSFER:last_created:reason=\"career_growth\" :approval_required=true",
			"",
			"// Exit process (if applicable)",
			"// EXIT.INITIATE employee_id=last_created type=\"voluntary\" reason=\"new_opportunity\"",
			"// EXIT:last_created:last_working_day=\"2025-12-31\" :handover_period=14",
			"// EXIT.CHECKLIST employee_id=last_created items=\"equipment_return,access_revocation,knowledge_transfer\"",
			"",
			"// === HR ANALYTICS ===",
			"// Employee engagement",
			"SURVEY.SEND type=\"engagement\" target=\"all_employees\" frequency=\"quarterly\"",
			"ANALYTICS.ENGAGEMENT period=\"2024-Q3\" segments=\"department,tenure,level\"",
			"",
			"// Retention analysis",
			"ANALYTICS.TURNOVER period=\"2024\" voluntary=true reasons=\"compensation,growth,culture\"",
			"ANALYTICS.RETENTION cohort=\"2023_hires\" period=\"24_months\"",
			"",
			"// Diversity and inclusion",
			"ANALYTICS.DIVERSITY dimensions=\"gender,ethnicity,age\" level=\"all_levels\"",
			"ANALYTICS.PAY-EQUITY groups=\"gender,ethnicity\" positions=\"similar_roles\"",
			"",
			"// Performance analytics",
			"ANALYTICS.PERFORMANCE distribution=\"rating_levels\" calibration=true",
			"ANALYTICS.PROMOTION-RATE period=\"2024\" segments=\"department,gender,ethnicity\"",
		},
		Context: map[string]interface{}{
			"company_size":     "500+ employees",
			"growth_rate":      "20% annually",
			"remote_policy":    "Hybrid/Remote friendly",
			"performance_cycle": "Quarterly check-ins, Annual reviews",
			"systems":          "HRIS, ATS, LMS integration",
		},
	}
	
	demo.scenarios = append(demo.scenarios, scenario)
	demo.logScenario(scenario)
	return scenario
}

// logScenario prints a formatted business scenario
func (demo *TCOLBusinessExamples) logScenario(scenario BusinessScenario) {
	fmt.Printf("\n" + strings.Repeat("=", 80) + "\n")
	fmt.Printf("BUSINESS SCENARIO: %s\n", scenario.Name)
	fmt.Printf("%s\n", strings.Repeat("=", 80))
	fmt.Printf("Description: %s\n\n", scenario.Description)
	
	// Print context information
	if len(scenario.Context) > 0 {
		fmt.Println("Context:")
		for key, value := range scenario.Context {
			fmt.Printf("  • %s: %v\n", key, value)
		}
		fmt.Println()
	}
	
	fmt.Println("TCOL Commands:")
	fmt.Println(strings.Repeat("-", 40))
	
	for i, cmd := range scenario.Commands {
		if strings.HasPrefix(cmd, "//") || strings.HasPrefix(cmd, "#") || strings.HasPrefix(cmd, "/*") {
			fmt.Printf("\n%s\n", cmd)
		} else if strings.TrimSpace(cmd) == "" {
			fmt.Println()
		} else {
			fmt.Printf("%3d. %s\n", i+1, cmd)
		}
	}
	
	fmt.Printf("\nTotal commands in scenario: %d\n", len(scenario.Commands))
}

// GetAllScenarios returns all business scenarios
func (demo *TCOLBusinessExamples) GetAllScenarios() []BusinessScenario {
	return demo.scenarios
}

// RunAllScenarios executes all business scenario demonstrations
func (demo *TCOLBusinessExamples) RunAllScenarios() {
	fmt.Println("TCOL BUSINESS SCENARIOS DEMONSTRATION")
	fmt.Println(strings.Repeat("=", 80))
	fmt.Printf("Generated: %s\n", time.Now().Format("2006-01-02 15:04:05"))
	
	demo.CustomerLifecycleManagement()
	demo.InvoiceProcessingWorkflow()
	demo.ProjectManagementScenario()
	demo.SalesProcessAutomation()
	demo.InventoryAndSupplyChain()
	demo.HRandTalentManagement()
	
	fmt.Printf("\n" + strings.Repeat("=", 80) + "\n")
	fmt.Printf("SUMMARY: %d business scenarios demonstrated\n", len(demo.scenarios))
	
	totalCommands := 0
	for _, scenario := range demo.scenarios {
		totalCommands += len(scenario.Commands)
	}
	fmt.Printf("Total TCOL commands across all scenarios: %d\n", totalCommands)
}